apiVersion: apps/v1
kind: Deployment
metadata:
  name: advertise-deployment
  labels:
    app: advertise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advertise
  template:
    metadata:
      labels:
        app: advertise
    spec:
      containers:
      - name: advertise
        image: flixtubekitti.azurecr.io/advertise:1
        env:
        - name: PORT
          value: "4000"
        - name: DBHOST
          value: mongodb://mongodb:27017
        - name: DBNAME
          value: metadata
        - name: RABBIT
          value: amqp://test:test@rabbit:5672
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: advertise
spec:
  selector:
    app: advertise
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
